name: stock-predictor
channels:
    - conda-forge
dependencies:
    - python=3.11
    - pip
    - pip:
        - streamlit
        - plotly
        - pandas
        - numpy
        - scikit-learn
        - tensorflow-cpu
        - ta
        - pandas-datareader